--- dbg/find14/find/find/Makefile	2020-01-28 23:48:53.000000000 -0600
+++ dbg/find6/find/find/Makefile	2020-01-28 23:39:58.000000000 -0600
@@ -15,6 +15,7 @@
 
 
 
+
 am__is_gnu_make = test -n '$(MAKEFILE_LIST)' && test -n '$(MAKELEVEL)'
 am__make_running_with_option = \
   case $${target_option-} in \
@@ -78,58 +79,100 @@ PRE_UNINSTALL = :
 POST_UNINSTALL = :
 build_triplet = x86_64-unknown-linux-gnu
 host_triplet = x86_64-unknown-linux-gnu
-bin_PROGRAMS = find$(EXEEXT)
+#bin_PROGRAMS = find$(EXEEXT) ftsfind$(EXEEXT)
+bin_PROGRAMS = find$(EXEEXT) oldfind$(EXEEXT)
 subdir = find
 DIST_COMMON = $(srcdir)/Makefile.in $(srcdir)/Makefile.am \
-	$(top_srcdir)/mkinstalldirs $(top_srcdir)/depcomp
+	$(top_srcdir)/build-aux/mkinstalldirs \
+	$(top_srcdir)/build-aux/depcomp
 ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
 am__aclocal_m4_deps = $(top_srcdir)/m4/findlib.m4 \
-	$(top_srcdir)/m4/nullsort.m4 $(top_srcdir)/gnulib/m4/alloca.m4 \
-	$(top_srcdir)/gnulib/m4/atexit.m4 \
+	$(top_srcdir)/m4/mkinstalldirs.m4 $(top_srcdir)/m4/nullsort.m4 \
+	$(top_srcdir)/m4/withfts.m4 \
+	$(top_srcdir)/gnulib/m4/absolute-header.m4 \
+	$(top_srcdir)/gnulib/m4/alloca.m4 \
+	$(top_srcdir)/gnulib/m4/allocsa.m4 \
+	$(top_srcdir)/gnulib/m4/argmatch.m4 \
+	$(top_srcdir)/gnulib/m4/bison.m4 \
 	$(top_srcdir)/gnulib/m4/canonicalize.m4 \
+	$(top_srcdir)/gnulib/m4/chdir-long.m4 \
+	$(top_srcdir)/gnulib/m4/chown.m4 \
+	$(top_srcdir)/gnulib/m4/clock_time.m4 \
+	$(top_srcdir)/gnulib/m4/close-stream.m4 \
 	$(top_srcdir)/gnulib/m4/closeout.m4 \
+	$(top_srcdir)/gnulib/m4/codeset.m4 \
+	$(top_srcdir)/gnulib/m4/cycle-check.m4 \
 	$(top_srcdir)/gnulib/m4/d-ino.m4 \
+	$(top_srcdir)/gnulib/m4/d-type.m4 \
+	$(top_srcdir)/gnulib/m4/dirfd.m4 \
 	$(top_srcdir)/gnulib/m4/dirname.m4 \
 	$(top_srcdir)/gnulib/m4/dos.m4 \
+	$(top_srcdir)/gnulib/m4/double-slash-root.m4 \
+	$(top_srcdir)/gnulib/m4/eealloc.m4 \
 	$(top_srcdir)/gnulib/m4/error.m4 \
 	$(top_srcdir)/gnulib/m4/exitfail.m4 \
 	$(top_srcdir)/gnulib/m4/extensions.m4 \
+	$(top_srcdir)/gnulib/m4/fcntl-safer.m4 \
+	$(top_srcdir)/gnulib/m4/fcntl_h.m4 \
 	$(top_srcdir)/gnulib/m4/fileblocks.m4 \
 	$(top_srcdir)/gnulib/m4/filemode.m4 \
+	$(top_srcdir)/gnulib/m4/filenamecat.m4 \
+	$(top_srcdir)/gnulib/m4/flexmember.m4 \
 	$(top_srcdir)/gnulib/m4/fnmatch.m4 \
 	$(top_srcdir)/gnulib/m4/fpending.m4 \
 	$(top_srcdir)/gnulib/m4/fstypename.m4 \
+	$(top_srcdir)/gnulib/m4/fts.m4 \
+	$(top_srcdir)/gnulib/m4/getcwd-abort-bug.m4 \
 	$(top_srcdir)/gnulib/m4/getcwd-path-max.m4 \
 	$(top_srcdir)/gnulib/m4/getcwd.m4 \
+	$(top_srcdir)/gnulib/m4/getdate.m4 \
+	$(top_srcdir)/gnulib/m4/getdelim.m4 \
 	$(top_srcdir)/gnulib/m4/getline.m4 \
-	$(top_srcdir)/gnulib/m4/getndelim2.m4 \
 	$(top_srcdir)/gnulib/m4/getopt.m4 \
 	$(top_srcdir)/gnulib/m4/gettext.m4 \
+	$(top_srcdir)/gnulib/m4/gettime.m4 \
 	$(top_srcdir)/gnulib/m4/gettimeofday.m4 \
-	$(top_srcdir)/gnulib/m4/gnulib.m4 \
+	$(top_srcdir)/gnulib/m4/glibc21.m4 \
+	$(top_srcdir)/gnulib/m4/gnulib-common.m4 \
+	$(top_srcdir)/gnulib/m4/gnulib-comp.m4 \
+	$(top_srcdir)/gnulib/m4/hash.m4 \
 	$(top_srcdir)/gnulib/m4/human.m4 \
+	$(top_srcdir)/gnulib/m4/i-ring.m4 \
 	$(top_srcdir)/gnulib/m4/iconv.m4 \
 	$(top_srcdir)/gnulib/m4/idcache.m4 \
-	$(top_srcdir)/gnulib/m4/intmax_t.m4 \
-	$(top_srcdir)/gnulib/m4/inttypes_h.m4 \
-	$(top_srcdir)/gnulib/m4/isc-posix.m4 \
+	$(top_srcdir)/gnulib/m4/inline.m4 \
+	$(top_srcdir)/gnulib/m4/inttypes-pri.m4 \
+	$(top_srcdir)/gnulib/m4/inttypes.m4 \
+	$(top_srcdir)/gnulib/m4/lchown.m4 \
 	$(top_srcdir)/gnulib/m4/lib-ld.m4 \
 	$(top_srcdir)/gnulib/m4/lib-link.m4 \
 	$(top_srcdir)/gnulib/m4/lib-prefix.m4 \
+	$(top_srcdir)/gnulib/m4/localcharset.m4 \
+	$(top_srcdir)/gnulib/m4/locale-fr.m4 \
+	$(top_srcdir)/gnulib/m4/locale-tr.m4 \
+	$(top_srcdir)/gnulib/m4/locale-zh.m4 \
+	$(top_srcdir)/gnulib/m4/longdouble.m4 \
 	$(top_srcdir)/gnulib/m4/longlong.m4 \
 	$(top_srcdir)/gnulib/m4/ls-mntd-fs.m4 \
 	$(top_srcdir)/gnulib/m4/lstat.m4 \
+	$(top_srcdir)/gnulib/m4/mbchar.m4 \
+	$(top_srcdir)/gnulib/m4/mbiter.m4 \
 	$(top_srcdir)/gnulib/m4/mbrtowc.m4 \
+	$(top_srcdir)/gnulib/m4/mbscasestr.m4 \
+	$(top_srcdir)/gnulib/m4/mbslen.m4 \
+	$(top_srcdir)/gnulib/m4/mbsstr.m4 \
 	$(top_srcdir)/gnulib/m4/mbstate_t.m4 \
+	$(top_srcdir)/gnulib/m4/memchr.m4 \
 	$(top_srcdir)/gnulib/m4/memcmp.m4 \
 	$(top_srcdir)/gnulib/m4/mempcpy.m4 \
+	$(top_srcdir)/gnulib/m4/memrchr.m4 \
 	$(top_srcdir)/gnulib/m4/memset.m4 \
 	$(top_srcdir)/gnulib/m4/mktime.m4 \
 	$(top_srcdir)/gnulib/m4/modechange.m4 \
 	$(top_srcdir)/gnulib/m4/mountlist.m4 \
 	$(top_srcdir)/gnulib/m4/nls.m4 \
 	$(top_srcdir)/gnulib/m4/onceonly_2_57.m4 \
-	$(top_srcdir)/gnulib/m4/path-concat.m4 \
+	$(top_srcdir)/gnulib/m4/openat.m4 \
 	$(top_srcdir)/gnulib/m4/pathmax.m4 \
 	$(top_srcdir)/gnulib/m4/po.m4 \
 	$(top_srcdir)/gnulib/m4/progtest.m4 \
@@ -137,48 +180,89 @@ am__aclocal_m4_deps = $(top_srcdir)/m4/f
 	$(top_srcdir)/gnulib/m4/quotearg.m4 \
 	$(top_srcdir)/gnulib/m4/readlink.m4 \
 	$(top_srcdir)/gnulib/m4/regex.m4 \
-	$(top_srcdir)/gnulib/m4/restrict.m4 \
 	$(top_srcdir)/gnulib/m4/rpmatch.m4 \
+	$(top_srcdir)/gnulib/m4/save-cwd.m4 \
 	$(top_srcdir)/gnulib/m4/savedir.m4 \
+	$(top_srcdir)/gnulib/m4/setenv.m4 \
 	$(top_srcdir)/gnulib/m4/ssize_t.m4 \
-	$(top_srcdir)/gnulib/m4/stat.m4 \
+	$(top_srcdir)/gnulib/m4/st_dm_mode.m4 \
+	$(top_srcdir)/gnulib/m4/stat-time.m4 \
 	$(top_srcdir)/gnulib/m4/stdbool.m4 \
-	$(top_srcdir)/gnulib/m4/stdint_h.m4 \
+	$(top_srcdir)/gnulib/m4/stdint.m4 \
+	$(top_srcdir)/gnulib/m4/stdio-safer.m4 \
+	$(top_srcdir)/gnulib/m4/stdlib_h.m4 \
 	$(top_srcdir)/gnulib/m4/stpcpy.m4 \
 	$(top_srcdir)/gnulib/m4/strdup.m4 \
-	$(top_srcdir)/gnulib/m4/strerror_r.m4 \
 	$(top_srcdir)/gnulib/m4/strftime.m4 \
-	$(top_srcdir)/gnulib/m4/strstr.m4 \
+	$(top_srcdir)/gnulib/m4/string_h.m4 \
+	$(top_srcdir)/gnulib/m4/strndup.m4 \
+	$(top_srcdir)/gnulib/m4/strnlen.m4 \
 	$(top_srcdir)/gnulib/m4/strtoimax.m4 \
 	$(top_srcdir)/gnulib/m4/strtol.m4 \
 	$(top_srcdir)/gnulib/m4/strtoll.m4 \
 	$(top_srcdir)/gnulib/m4/strtoul.m4 \
 	$(top_srcdir)/gnulib/m4/strtoull.m4 \
 	$(top_srcdir)/gnulib/m4/strtoumax.m4 \
+	$(top_srcdir)/gnulib/m4/sys_stat_h.m4 \
+	$(top_srcdir)/gnulib/m4/sys_time_h.m4 \
+	$(top_srcdir)/gnulib/m4/time_h.m4 \
 	$(top_srcdir)/gnulib/m4/time_r.m4 \
+	$(top_srcdir)/gnulib/m4/timespec.m4 \
 	$(top_srcdir)/gnulib/m4/tm_gmtoff.m4 \
-	$(top_srcdir)/gnulib/m4/tzset.m4 \
-	$(top_srcdir)/gnulib/m4/uintmax_t.m4 \
 	$(top_srcdir)/gnulib/m4/ulonglong.m4 \
+	$(top_srcdir)/gnulib/m4/unistd-safer.m4 \
+	$(top_srcdir)/gnulib/m4/unistd_h.m4 \
+	$(top_srcdir)/gnulib/m4/wchar.m4 \
+	$(top_srcdir)/gnulib/m4/wchar_t.m4 \
+	$(top_srcdir)/gnulib/m4/wctype.m4 \
+	$(top_srcdir)/gnulib/m4/wcwidth.m4 \
+	$(top_srcdir)/gnulib/m4/wint_t.m4 \
 	$(top_srcdir)/gnulib/m4/xalloc.m4 \
 	$(top_srcdir)/gnulib/m4/xgetcwd.m4 \
-	$(top_srcdir)/gnulib/m4/xreadlink.m4 \
+	$(top_srcdir)/gnulib/m4/xstrndup.m4 \
+	$(top_srcdir)/gnulib/m4/xstrtod.m4 \
 	$(top_srcdir)/gnulib/m4/xstrtol.m4 \
-	$(top_srcdir)/gnulib/m4/xstrtoumax.m4 \
 	$(top_srcdir)/gnulib/m4/yesno.m4 $(top_srcdir)/configure.in
 am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
 	$(ACLOCAL_M4)
-mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
+mkinstalldirs = $(SHELL) $(top_srcdir)/build-aux/mkinstalldirs
 CONFIG_HEADER = $(top_builddir)/config.h
 CONFIG_CLEAN_FILES =
 CONFIG_CLEAN_VPATH_FILES =
+LIBRARIES = $(noinst_LIBRARIES)
+AR = ar
+ARFLAGS = cru
+AM_V_AR = $(am__v_AR_$(V))
+am__v_AR_ = $(am__v_AR_$(AM_DEFAULT_VERBOSITY))
+am__v_AR_0 = @echo "  AR      " $@;
+am__v_AR_1 = 
+libfindtools_a_AR = $(AR) $(ARFLAGS)
+libfindtools_a_LIBADD =
+am_libfindtools_a_OBJECTS = finddata.$(OBJEXT) fstype.$(OBJEXT) \
+	parser.$(OBJEXT) pred.$(OBJEXT) tree.$(OBJEXT) util.$(OBJEXT) \
+	version.$(OBJEXT)
+libfindtools_a_OBJECTS = $(am_libfindtools_a_OBJECTS)
 am__installdirs = "$(DESTDIR)$(bindir)" "$(DESTDIR)$(man1dir)"
 PROGRAMS = $(bin_PROGRAMS)
-am_find_OBJECTS = find.$(OBJEXT) fstype.$(OBJEXT) parser.$(OBJEXT) \
-	pred.$(OBJEXT) tree.$(OBJEXT) util.$(OBJEXT) version.$(OBJEXT)
+am__find_SOURCES_DIST = find.c ftsfind.c
+#am_find_OBJECTS = find.$(OBJEXT)
+am_find_OBJECTS = ftsfind.$(OBJEXT)
 find_OBJECTS = $(am_find_OBJECTS)
 find_LDADD = $(LDADD)
-find_DEPENDENCIES = ../lib/libfind.a ../gnulib/lib/libgnulib.a
+find_DEPENDENCIES = ./libfindtools.a ../lib/libfind.a \
+	../gnulib/lib/libgnulib.a
+am__ftsfind_SOURCES_DIST = ftsfind.c
+#am_ftsfind_OBJECTS = ftsfind.$(OBJEXT)
+ftsfind_OBJECTS = $(am_ftsfind_OBJECTS)
+ftsfind_LDADD = $(LDADD)
+ftsfind_DEPENDENCIES = ./libfindtools.a ../lib/libfind.a \
+	../gnulib/lib/libgnulib.a
+am__oldfind_SOURCES_DIST = find.c
+am_oldfind_OBJECTS = find.$(OBJEXT)
+oldfind_OBJECTS = $(am_oldfind_OBJECTS)
+oldfind_LDADD = $(LDADD)
+oldfind_DEPENDENCIES = ./libfindtools.a ../lib/libfind.a \
+	../gnulib/lib/libgnulib.a
 AM_V_P = $(am__v_P_$(V))
 am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
 am__v_P_0 = false
@@ -192,7 +276,7 @@ am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERB
 am__v_at_0 = @
 am__v_at_1 = 
 DEFAULT_INCLUDES = -I. -I$(top_builddir)
-depcomp = $(SHELL) $(top_srcdir)/depcomp
+depcomp = $(SHELL) $(top_srcdir)/build-aux/depcomp
 am__depfiles_maybe = depfiles
 am__mv = mv -f
 COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
@@ -207,8 +291,10 @@ AM_V_CCLD = $(am__v_CCLD_$(V))
 am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
 am__v_CCLD_0 = @echo "  CCLD    " $@;
 am__v_CCLD_1 = 
-SOURCES = $(find_SOURCES)
-DIST_SOURCES = $(find_SOURCES)
+SOURCES = $(libfindtools_a_SOURCES) $(find_SOURCES) $(ftsfind_SOURCES) \
+	$(oldfind_SOURCES)
+DIST_SOURCES = $(libfindtools_a_SOURCES) $(am__find_SOURCES_DIST) \
+	$(am__ftsfind_SOURCES_DIST) $(am__oldfind_SOURCES_DIST)
 RECURSIVE_TARGETS = all-recursive check-recursive cscopelist-recursive \
 	ctags-recursive dvi-recursive html-recursive info-recursive \
 	install-data-recursive install-dvi-recursive \
@@ -306,6 +392,17 @@ am__relativize = \
     dir1=`echo "$$dir1" | sed -e "$$sed_rest"`; \
   done; \
   reldir="$$dir2"
+ABSOLUTE_FCNTL_H = "///usr/include/fcntl.h"
+ABSOLUTE_INTTYPES_H = "///usr/include/inttypes.h"
+ABSOLUTE_STDINT_H = "///usr/lib/gcc/x86_64-linux-gnu/4.8/include/stdint.h"
+ABSOLUTE_STDLIB_H = "///usr/include/stdlib.h"
+ABSOLUTE_STRING_H = "///usr/include/string.h"
+ABSOLUTE_SYS_STAT_H = "///usr/include/x86_64-linux-gnu/sys/stat.h"
+ABSOLUTE_SYS_TIME_H = "///usr/include/x86_64-linux-gnu/sys/time.h"
+ABSOLUTE_TIME_H = "///usr/include/time.h"
+ABSOLUTE_UNISTD_H = "///usr/include/unistd.h"
+ABSOLUTE_WCHAR_H = 
+ABSOLUTE_WCTYPE_H = "///usr/include/wctype.h"
 ACLOCAL = aclocal-1.14
 ALLOCA = 
 ALLOCA_H = alloca.h
@@ -314,7 +411,13 @@ AM_DEFAULT_VERBOSITY = 1
 AUTOCONF = autoconf
 AUTOHEADER = autoheader
 AUTOMAKE = automake-1.14
+AUXDIR = build-aux
 AWK = mawk
+BITSIZEOF_PTRDIFF_T = 
+BITSIZEOF_SIG_ATOMIC_T = 
+BITSIZEOF_SIZE_T = 
+BITSIZEOF_WCHAR_T = 
+BITSIZEOF_WINT_T = 
 CC = gcc
 CCDEPMODE = depmode=gcc3
 CFLAGS = -g -O2
@@ -328,11 +431,95 @@ ECHO_N = -n
 ECHO_T = 
 EGREP = /bin/grep -E
 EXEEXT = 
+FCNTL_H = fcntl.h
 FINDLIBOBJS =  forcefindlib.o
 FNMATCH_H = 
 GETOPT_H = 
+GLIBC21 = yes
 GMSGFMT = /usr/bin/msgfmt
+GMSGFMT_015 = /usr/bin/msgfmt
+GNULIB_CHOWN = 1
+GNULIB_DUP2 = 0
+GNULIB_FCHDIR = 0
+GNULIB_FTRUNCATE = 0
+GNULIB_GETCWD = 1
+GNULIB_GETLOGIN_R = 0
+GNULIB_GETSUBOPT = 0
+GNULIB_IMAXABS = 0
+GNULIB_IMAXDIV = 0
+GNULIB_MBSCASECMP = 0
+GNULIB_MBSCASESTR = 1
+GNULIB_MBSCHR = 0
+GNULIB_MBSCSPN = 0
+GNULIB_MBSLEN = 1
+GNULIB_MBSNCASECMP = 0
+GNULIB_MBSPBRK = 0
+GNULIB_MBSPCASECMP = 0
+GNULIB_MBSRCHR = 0
+GNULIB_MBSSEP = 0
+GNULIB_MBSSPN = 0
+GNULIB_MBSSTR = 1
+GNULIB_MBSTOK_R = 0
+GNULIB_MEMMEM = 0
+GNULIB_MEMPCPY = 1
+GNULIB_MEMRCHR = 1
+GNULIB_MKDTEMP = 0
+GNULIB_MKSTEMP = 0
+GNULIB_READLINK = 1
+GNULIB_STPCPY = 1
+GNULIB_STPNCPY = 0
+GNULIB_STRCASESTR = 0
+GNULIB_STRCHRNUL = 0
+GNULIB_STRDUP = 1
+GNULIB_STRNDUP = 1
+GNULIB_STRNLEN = 1
+GNULIB_STRPBRK = 0
+GNULIB_STRSEP = 0
+GNULIB_STRTOIMAX = 1
+GNULIB_STRTOK_R = 0
+GNULIB_STRTOUMAX = 1
 GREP = /bin/grep
+HAVE_DECL_GETLOGIN_R = 1
+HAVE_DECL_IMAXABS = 1
+HAVE_DECL_IMAXDIV = 1
+HAVE_DECL_MEMMEM = 1
+HAVE_DECL_MEMRCHR = 1
+HAVE_DECL_STRDUP = 1
+HAVE_DECL_STRNCASECMP = 1
+HAVE_DECL_STRNDUP = 1
+HAVE_DECL_STRNLEN = 1
+HAVE_DECL_STRTOIMAX = 1
+HAVE_DECL_STRTOK_R = 1
+HAVE_DECL_STRTOUMAX = 1
+HAVE_DUP2 = 1
+HAVE_FTRUNCATE = 1
+HAVE_GETSUBOPT = 1
+HAVE_INTTYPES_H = 1
+HAVE_LONG_LONG_INT = 1
+HAVE_MEMPCPY = 1
+HAVE_MKDTEMP = 1
+HAVE_READLINK = 1
+HAVE_SIGNED_SIG_ATOMIC_T = 
+HAVE_SIGNED_WCHAR_T = 
+HAVE_SIGNED_WINT_T = 
+HAVE_STDINT_H = 1
+HAVE_STPCPY = 1
+HAVE_STPNCPY = 1
+HAVE_STRCASECMP = 1
+HAVE_STRCASESTR = 1
+HAVE_STRCHRNUL = 1
+HAVE_STRNDUP = 1
+HAVE_STRPBRK = 1
+HAVE_STRSEP = 1
+HAVE_STRUCT_TIMEVAL = 1
+HAVE_SYS_BITYPES_H = 
+HAVE_SYS_INTTYPES_H = 
+HAVE_SYS_TIME_H = 1
+HAVE_SYS_TYPES_H = 1
+HAVE_UNISTD_H = 1
+HAVE_UNSIGNED_LONG_LONG_INT = 1
+HAVE_WCTYPE_H = 1
+HAVE_WINT_T = 1
 HAVE__BOOL = 1
 INCLUDES = -I../gnulib/lib -I$(top_srcdir)/lib -I$(top_srcdir)/gnulib/lib -I../intl -DLOCALEDIR=\"$(localedir)\"
 INSTALL = /usr/bin/install -c
@@ -341,43 +528,78 @@ INSTALL_PROGRAM = ${INSTALL}
 INSTALL_SCRIPT = ${INSTALL}
 INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
 INTLLIBS = 
+INTL_MACOSX_LIBS = 
+INTTYPES_H = inttypes.h
 LDFLAGS = 
+LIBGNULIB_LIBDEPS = 
+LIBGNULIB_LTLIBDEPS = 
 LIBICONV = -liconv
 LIBINTL = 
-LIBOBJS =  ${LIBOBJDIR}mktime$U.o ${LIBOBJDIR}getcwd$U.o ${LIBOBJDIR}mountlist$U.o
+LIBOBJS =  ${LIBOBJDIR}regex$U.o
 LIBS = 
+LIB_CLOCK_GETTIME = 
+LOCALE_FR_UTF8 = none
+LOCALE_TR_UTF8 = tr_TR.UTF-8
+LOCALE_ZH_CN = none
 LTLIBICONV = -liconv
 LTLIBINTL = 
-LTLIBOBJS =  ${LIBOBJDIR}mktime$U.lo ${LIBOBJDIR}getcwd$U.lo ${LIBOBJDIR}mountlist$U.lo
+LTLIBOBJS =  ${LIBOBJDIR}regex$U.lo
 MAKEINFO = makeinfo
 MKDIR_P = /bin/mkdir -p
-MKINSTALLDIRS = $(top_builddir)/./mkinstalldirs
+MKINSTALLDIRS = $(top_builddir)/build-aux/mkinstalldirs
 MSGFMT = /usr/bin/msgfmt
+MSGFMT_015 = /usr/bin/msgfmt
 MSGMERGE = /usr/bin/msgmerge
 OBJEXT = o
 PACKAGE = findutils
-PACKAGE_BUGREPORT = 
-PACKAGE_NAME = 
-PACKAGE_STRING = 
-PACKAGE_TARNAME = 
-PACKAGE_URL = 
-PACKAGE_VERSION = 
+PACKAGE_BUGREPORT = bug-findutils@gnu.org
+PACKAGE_NAME = GNU findutils
+PACKAGE_STRING = GNU findutils 4.3.3-CVS
+PACKAGE_TARNAME = findutils
+PACKAGE_URL = http://www.gnu.org/software/findutils/
+PACKAGE_VERSION = 4.3.3-CVS
 PATH_SEPARATOR = :
 POSUB = 
+PRIPTR_PREFIX = "l"
+PRI_MACROS_BROKEN = 0
+PTRDIFF_T_SUFFIX = 
 RANLIB = ranlib
+REPLACE_CHOWN = 0
+REPLACE_FCHDIR = 0
+REPLACE_GETCWD = 0
+REPLACE_GETTIMEOFDAY = 0
+REPLACE_LOCALTIME_R = 0
+REPLACE_MKSTEMP = 0
+REPLACE_NANOSLEEP = GNULIB_PORTCHECK
+REPLACE_STRPTIME = GNULIB_PORTCHECK
+REPLACE_TIMEGM = GNULIB_PORTCHECK
 SET_MAKE = 
 SHELL = /bin/bash
+SIG_ATOMIC_T_SUFFIX = 
+SIZE_T_SUFFIX = 
 SORT = /usr/bin/sort
 SORT_SUPPORTS_Z = true
 STDBOOL_H = 
+STDINT_H = 
 STRIP = 
+SYS_STAT_H = sys/stat.h
+SYS_TIME_H = 
+SYS_TIME_H_DEFINES_STRUCT_TIMESPEC = 0
+TIME_H_DEFINES_STRUCT_TIMESPEC = 1
 USE_NLS = no
-VERSION = 4.2.18-CVS
+VERSION = 4.3.3-CVS
+WCHAR_H = 
+WCHAR_T_SUFFIX = 
+WCTYPE_H = 
+WINT_T_SUFFIX = 
 XGETTEXT = /usr/bin/xgettext
-abs_builddir = /root/Desktop/find14/find/find
-abs_srcdir = /root/Desktop/find14/find/find
-abs_top_builddir = /root/Desktop/find14/find
-abs_top_srcdir = /root/Desktop/find14/find
+XGETTEXT_015 = /usr/bin/xgettext
+YACC = bison -y
+YFLAGS = 
+abs_builddir = /root/Desktop/find6/find/find
+abs_srcdir = /root/Desktop/find6/find/find
+abs_top_builddir = /root/Desktop/find6/find
+abs_top_srcdir = /root/Desktop/find6/find
 ac_ct_CC = gcc
 am__include = include
 am__leading_dot = .
@@ -393,9 +615,11 @@ build_vendor = unknown
 builddir = .
 datadir = ${datarootdir}
 datarootdir = ${prefix}/share
-docdir = ${datarootdir}/doc/${PACKAGE}
+docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
 dvidir = ${docdir}
 exec_prefix = ${prefix}
+gl_LIBOBJS =  argmatch.o basename.o canonicalize.o chdir-long.o close-stream.o closeout.o creat-safer.o cycle-check.o dirname.o dup-safer.o exitfail.o fchownat.o fd-safer.o filemode.o filenamecat.o fopen-safer.o fstatat.o fts.o gettime.o hash.o human.o i-ring.o idcache.o modechange.o mountlist.o open-safer.o openat-die.o openat-proc.o pipe-safer.o quote.o quotearg.o regex.o save-cwd.o savedir.o strftime.o stripslash.o xgetcwd.o xmalloc.o xstrtod.o xstrtol.o xstrtoul.o yesno.o
+gl_LTLIBOBJS =  argmatch.lo basename.lo canonicalize.lo chdir-long.lo close-stream.lo closeout.lo creat-safer.lo cycle-check.lo dirname.lo dup-safer.lo exitfail.lo fchownat.lo fd-safer.lo filemode.lo filenamecat.lo fopen-safer.lo fstatat.lo fts.lo gettime.lo hash.lo human.lo i-ring.lo idcache.lo modechange.lo mountlist.lo open-safer.lo openat-die.lo openat-proc.lo pipe-safer.lo quote.lo quotearg.lo regex.lo save-cwd.lo savedir.lo strftime.lo stripslash.lo xgetcwd.lo xmalloc.lo xstrtod.lo xstrtol.lo xstrtoul.lo yesno.lo
 host = x86_64-unknown-linux-gnu
 host_alias = 
 host_cpu = x86_64
@@ -404,13 +628,13 @@ host_vendor = unknown
 htmldir = ${docdir}
 includedir = ${prefix}/include
 infodir = ${datarootdir}/info
-install_sh = ${SHELL} /root/Desktop/find14/find/install-sh
+install_sh = ${SHELL} /root/Desktop/find6/find/build-aux/install-sh
 libdir = ${exec_prefix}/lib
 libexecdir = ${exec_prefix}/libexec
 localedir = $(datadir)/locale
 localstatedir = ${prefix}/var
 mandir = ${datarootdir}/man
-mkdir_p = $(MKDIR_P)
+mkdir_p = /bin/mkdir -p
 oldincludedir = /usr/include
 pdfdir = ${docdir}
 prefix = /usr/local
@@ -425,9 +649,16 @@ top_build_prefix = ../
 top_builddir = ..
 top_srcdir = ..
 AUTOMAKE_OPTIONS = std-options
-find_SOURCES = find.c fstype.c parser.c pred.c tree.c util.c version.c
+# noinst_PROGRAMS = regexprops
+# regexprops_SOURCES = regexprops.c
+noinst_LIBRARIES = libfindtools.a
+libfindtools_a_SOURCES = finddata.c fstype.c parser.c pred.c tree.c util.c version.c
+#find_SOURCES = find.c
+find_SOURCES = ftsfind.c
+oldfind_SOURCES = find.c
+#ftsfind_SOURCES = ftsfind.c
 EXTRA_DIST = defs.h $(man_MANS)
-LDADD = ../lib/libfind.a ../gnulib/lib/libgnulib.a 
+LDADD = ./libfindtools.a ../lib/libfind.a ../gnulib/lib/libgnulib.a  
 man_MANS = find.1
 SUBDIRS = testsuite
 all: all-recursive
@@ -464,6 +695,14 @@ $(top_srcdir)/configure:  $(am__configur
 $(ACLOCAL_M4):  $(am__aclocal_m4_deps)
 	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
 $(am__aclocal_m4_deps):
+
+clean-noinstLIBRARIES:
+	-test -z "$(noinst_LIBRARIES)" || rm -f $(noinst_LIBRARIES)
+
+libfindtools.a: $(libfindtools_a_OBJECTS) $(libfindtools_a_DEPENDENCIES) $(EXTRA_libfindtools_a_DEPENDENCIES) 
+	$(AM_V_at)-rm -f libfindtools.a
+	$(AM_V_AR)$(libfindtools_a_AR) libfindtools.a $(libfindtools_a_OBJECTS) $(libfindtools_a_LIBADD)
+	$(AM_V_at)$(RANLIB) libfindtools.a
 install-binPROGRAMS: $(bin_PROGRAMS)
 	@$(NORMAL_INSTALL)
 	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
@@ -527,6 +766,14 @@ find$(EXEEXT): $(find_OBJECTS) $(find_DE
 	@rm -f find$(EXEEXT)
 	$(AM_V_CCLD)$(LINK) $(find_OBJECTS) $(find_LDADD) $(LIBS)
 
+ftsfind$(EXEEXT): $(ftsfind_OBJECTS) $(ftsfind_DEPENDENCIES) $(EXTRA_ftsfind_DEPENDENCIES) 
+	@rm -f ftsfind$(EXEEXT)
+	$(AM_V_CCLD)$(LINK) $(ftsfind_OBJECTS) $(ftsfind_LDADD) $(LIBS)
+
+oldfind$(EXEEXT): $(oldfind_OBJECTS) $(oldfind_DEPENDENCIES) $(EXTRA_oldfind_DEPENDENCIES) 
+	@rm -f oldfind$(EXEEXT)
+	$(AM_V_CCLD)$(LINK) $(oldfind_OBJECTS) $(oldfind_LDADD) $(LIBS)
+
 mostlyclean-compile:
 	-rm -f *.$(OBJEXT)
 
@@ -534,7 +781,9 @@ distclean-compile:
 	-rm -f *.tab.c
 
 include ./$(DEPDIR)/find.Po
+include ./$(DEPDIR)/finddata.Po
 include ./$(DEPDIR)/fstype.Po
+include ./$(DEPDIR)/ftsfind.Po
 include ./$(DEPDIR)/parser.Po
 include ./$(DEPDIR)/pred.Po
 include ./$(DEPDIR)/tree.Po
@@ -754,7 +1003,7 @@ distdir: $(DISTFILES)
 	done
 check-am: all-am
 check: check-recursive
-all-am: Makefile $(PROGRAMS) $(MANS)
+all-am: Makefile $(LIBRARIES) $(PROGRAMS) $(MANS)
 installdirs: installdirs-recursive
 installdirs-am:
 	for dir in "$(DESTDIR)$(bindir)" "$(DESTDIR)$(man1dir)"; do \
@@ -792,7 +1041,8 @@ maintainer-clean-generic:
 	@echo "it deletes files that may require special tools to rebuild."
 clean: clean-recursive
 
-clean-am: clean-binPROGRAMS clean-generic mostlyclean-am
+clean-am: clean-binPROGRAMS clean-generic clean-noinstLIBRARIES \
+	mostlyclean-am
 
 distclean: distclean-recursive
 	-rm -rf ./$(DEPDIR)
@@ -864,20 +1114,20 @@ uninstall-man: uninstall-man1
 .MAKE: $(am__recursive_targets) install-am install-strip
 
 .PHONY: $(am__recursive_targets) CTAGS GTAGS TAGS all all-am check \
-	check-am clean clean-binPROGRAMS clean-generic cscopelist-am \
-	ctags ctags-am distclean distclean-compile distclean-generic \
-	distclean-tags distdir dvi dvi-am html html-am info info-am \
-	install install-am install-binPROGRAMS install-data \
-	install-data-am install-dvi install-dvi-am install-exec \
-	install-exec-am install-html install-html-am install-info \
-	install-info-am install-man install-man1 install-pdf \
-	install-pdf-am install-ps install-ps-am install-strip \
-	installcheck installcheck-am installcheck-binPROGRAMS \
-	installdirs installdirs-am maintainer-clean \
-	maintainer-clean-generic mostlyclean mostlyclean-compile \
-	mostlyclean-generic pdf pdf-am ps ps-am tags tags-am uninstall \
-	uninstall-am uninstall-binPROGRAMS uninstall-man \
-	uninstall-man1
+	check-am clean clean-binPROGRAMS clean-generic \
+	clean-noinstLIBRARIES cscopelist-am ctags ctags-am distclean \
+	distclean-compile distclean-generic distclean-tags distdir dvi \
+	dvi-am html html-am info info-am install install-am \
+	install-binPROGRAMS install-data install-data-am install-dvi \
+	install-dvi-am install-exec install-exec-am install-html \
+	install-html-am install-info install-info-am install-man \
+	install-man1 install-pdf install-pdf-am install-ps \
+	install-ps-am install-strip installcheck installcheck-am \
+	installcheck-binPROGRAMS installdirs installdirs-am \
+	maintainer-clean maintainer-clean-generic mostlyclean \
+	mostlyclean-compile mostlyclean-generic pdf pdf-am ps ps-am \
+	tags tags-am uninstall uninstall-am uninstall-binPROGRAMS \
+	uninstall-man uninstall-man1
 
 
 #$(PROGRAMS): ../lib/libfind.a
diff -up -r dbg/find14/find/find/Makefile.am dbg/find6/find/find/Makefile.am
